"""
Pydantic Schemas for AI-Powered Company & Lead Enrichment API.
Defines strict schemas for search refinement, cadastral data, digital presence,
market positioning, and commercial intelligence.
"""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class SearchRefinementPlan(BaseModel):
    """Generated by Gemini to formulate optimal Google search queries based on the company name."""
    primary_query: str = Field(description="Busca para identificar site oficial e apresentação institucional")
    fiscal_query: str = Field(description="Busca direcionada para CNPJ, Razão Social e dados cadastrais públicos")
    social_query: str = Field(description="Busca para Company Page no LinkedIn e perfil corporativo")
    assumptions_and_context: str = Field(description="Inferências iniciais sobre possíveis homônimos ou ramo provável")


class CadastralData(BaseModel):
    """Dados cadastrais e societários públicos da empresa."""
    razao_social: Optional[str] = Field(default=None, description="Razão Social completa oficial")
    nome_fantasia: str = Field(description="Nome fantasia ou marca comercial")
    cnpj: Optional[str] = Field(default=None, description="Número de CNPJ (formatado ou não), se identificado")
    situacao_cadastral: Optional[str] = Field(default=None, description="Situação cadastral (ex: Ativa, Baixada) se identificada")
    data_abertura: Optional[str] = Field(default=None, description="Ano ou data de fundação/abertura se mencionada")
    sede_localizacao: Optional[str] = Field(default=None, description="Cidade, Estado ou endereço da matriz")


class DigitalPresence(BaseModel):
    """Canais e presenças digitais identificadas."""
    website_oficial: Optional[str] = Field(default=None, description="URL limpa do site oficial da empresa")
    linkedin_url: Optional[str] = Field(default=None, description="URL da Company Page no LinkedIn")
    telefones: List[str] = Field(default_factory=list, description="Telefones institucionais ou de atendimento")
    emails: List[str] = Field(default_factory=list, description="E-mails corporativos (contato, comercial, etc.)")
    outras_redes: Dict[str, str] = Field(default_factory=dict, description="Outros links (Instagram, YouTube, etc.)")


class MarketProfile(BaseModel):
    """Posicionamento de mercado, porte e soluções."""
    setor_atuacao: str = Field(description="Setor primário (ex: Tecnologia, Fintech, Logística, Agronegócio, Saúde)")
    subsetor_nicho: Optional[str] = Field(default=None, description="Nicho específico de atuação")
    porte_estimado: str = Field(description="Porte estimado: Startup, ME/EPP, PME ou Grande Empresa / Enterprise")
    descricao_negocio: str = Field(description="Resumo conciso de 2-4 frases explicando como a empresa gera valor e o que vende")
    principais_produtos_ou_servicos: List[str] = Field(default_factory=list, description="Lista dos principais produtos ou serviços oferecidos")
    modelo_negocio: Optional[str] = Field(default=None, description="B2B, B2C, B2B2C, SaaS, Marketplace, Indústria, etc.")


class CommercialIntelligence(BaseModel):
    """Inteligência tática gerada pela IA para apoiar vendas/SDR."""
    dor_de_mercado_resolvida: Optional[str] = Field(default=None, description="Principal dor ou problema que a empresa resolve para seus clientes")
    sugestao_pitch_vendas: str = Field(description="Dica estratégica de abordagem comercial ou gancho para iniciar uma conversa de vendas")
    nivel_confianca: Literal["ALTA", "MEDIA", "BAIXA"] = Field(
        default="MEDIA",
        description="Nível de confiabilidade das informações encontradas com base na clareza dos dados públicos"
    )
    fontes_consultadas: List[str] = Field(default_factory=list, description="URLs de referência ou portais públicos utilizados")


class CompanyEnrichmentRequest(BaseModel):
    """Requisição de enriquecimento de empresa."""
    company_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Nome da empresa a ser enriquecida",
        examples=["Matera", "Kavak", "Totvs", "Padaria Real Sorocaba"],
    )
    location_hint: Optional[str] = Field(
        default=None,
        description="Dica de localização (cidade ou estado) para desambiguação",
        examples=["Campinas SP", "São Paulo", "Belo Horizonte"],
    )
    segment_hint: Optional[str] = Field(
        default=None,
        description="Dica de segmento de mercado para afunilar empresas homônimas",
        examples=["Fintech", "Software", "Alimentos", "Logística"],
    )
    deep_scrape_website: bool = Field(
        default=True,
        description="Se true, faz o download do conteúdo da página oficial identificada para extração mais profunda",
    )


class CompanyEnrichmentResponse(BaseModel):
    """Resposta estruturada de enriquecimento de empresa."""
    status: str = Field(default="SUCCESS")
    nome_pesquisado: str
    dados_cadastrais: CadastralData
    presenca_digital: DigitalPresence
    perfil_mercado: MarketProfile
    inteligencia_comercial: CommercialIntelligence
    execution_time_seconds: Optional[float] = None
