"""
Pydantic Schemas for AI-Powered Company & Lead Enrichment API.
Defines strict schemas for search refinement, cadastral data, digital presence,
market positioning, and commercial intelligence.
"""

import re
from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import BaseModel, Field, model_validator


def _normalize_string_list(val: Any) -> List[str]:
    """Flattens and normalizes comma-separated strings or string lists into a clean unique list."""
    if not val:
        return []
    if isinstance(val, list):
        res = []
        for x in val:
            if isinstance(x, str):
                for part in re.split(r"[,;\n]+", x):
                    s = part.strip()
                    if s and s not in res:
                        res.append(s)
            elif x:
                s = str(x).strip()
                if s and s not in res:
                    res.append(s)
        return res
    if isinstance(val, str):
        res = []
        for part in re.split(r"[,;\n]+", val):
            s = part.strip()
            if s and s not in res:
                res.append(s)
        return res
    return []


class ContactInput(BaseModel):
    """Contato opcional de lead ou executivo fornecido na requisição."""
    nome: Optional[str] = Field(default=None, description="Nome completo da pessoa")
    email: Optional[str] = Field(default=None, description="E-mail profissional ou pessoal")
    telefone: Optional[str] = Field(default=None, description="Telefone fixo ou WhatsApp")
    cargo: Optional[str] = Field(default=None, description="Cargo ou área da pessoa, se conhecido")

    @model_validator(mode="before")
    @classmethod
    def resolve_contact_aliases(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for alt in ["name", "full_name", "pessoa", "person"]:
                if alt in data and not data.get("nome"):
                    data["nome"] = data[alt]
            for alt in ["mail", "e-mail"]:
                if alt in data and not data.get("email"):
                    data["email"] = data[alt]
            for alt in ["phone", "celular", "whatsapp", "tel"]:
                if alt in data and not data.get("telefone"):
                    data["telefone"] = data[alt]
            for alt in ["role", "position", "title"]:
                if alt in data and not data.get("cargo"):
                    data["cargo"] = data[alt]
        return data


class SearchRefinementPlan(BaseModel):
    """Generated by Gemini to formulate optimal Google search queries based on the company name."""
    primary_query: str = Field(description="Busca para identificar site oficial e apresentação institucional")
    fiscal_query: str = Field(description="Busca direcionada para CNPJ, Razão Social e dados cadastrais públicos")
    social_query: str = Field(description="Busca para Company Page no LinkedIn e perfil corporativo")
    assumptions_and_context: str = Field(description="Inferências iniciais sobre possíveis homônimos ou ramo provável")


class CadastralData(BaseModel):
    """Dados cadastrais e societários públicos da empresa."""
    razao_social: Optional[str] = Field(default=None, description="Razão Social completa oficial")
    nome_fantasia: Optional[str] = Field(default=None, description="Nome fantasia ou marca comercial")
    cnpj: Optional[str] = Field(default=None, description="Número de CNPJ (formatado ou não), se identificado")
    situacao_cadastral: Optional[str] = Field(default=None, description="Situação cadastral (ex: Ativa, Baixada) se identificada")
    data_abertura: Optional[str] = Field(default=None, description="Ano ou data de fundação/abertura se mencionada")
    sede_localizacao: Optional[str] = Field(default=None, description="Cidade, Estado ou endereço da matriz")
    qsa: List[Dict[str, Any]] = Field(default_factory=list, description="Quadro de Sócios e Administradores (QSA)")


class DigitalPresence(BaseModel):
    """Canais e presenças digitais identificadas."""
    website_oficial: Optional[str] = Field(default=None, description="URL limpa do site oficial da empresa")
    linkedin_url: Optional[str] = Field(default=None, description="URL da Company Page no LinkedIn")
    telefones: List[str] = Field(default_factory=list, description="Telefones institucionais ou de atendimento")
    emails: List[str] = Field(default_factory=list, description="E-mails corporativos (contato, comercial, etc.)")
    outras_redes: List[str] = Field(default_factory=list, description="Outros links (Instagram, YouTube, etc.)")


class MarketProfile(BaseModel):
    """Posicionamento de mercado, porte e soluções."""
    setor_atuacao: str = Field(description="Setor primário (ex: Tecnologia, Fintech, Logística, Agronegócio, Saúde)")
    subsetor_nicho: Optional[str] = Field(default=None, description="Nicho específico de atuação")
    porte_estimado: str = Field(description="Porte estimado: Startup, ME/EPP, PME ou Grande Empresa / Enterprise")
    descricao_negocio: str = Field(description="Resumo conciso de 2-4 frases explicando como a empresa gera valor e o que vende")
    principais_produtos_ou_servicos: List[str] = Field(default_factory=list, description="Lista dos principais produtos ou serviços oferecidos")
    modelo_negocio: Optional[str] = Field(default=None, description="B2B, B2C, B2B2C, SaaS, Marketplace, Indústria, etc.")


class CommercialIntelligence(BaseModel):
    """Inteligência tática gerada pela IA para apoiar vendas/SDR."""
    dor_de_mercado_resolvida: Optional[str] = Field(default=None, description="Principal dor ou problema que a empresa resolve para seus clientes")
    sugestao_pitch_vendas: str = Field(description="Dica estratégica de abordagem comercial ou gancho para iniciar uma conversa de vendas")
    nivel_confianca: Literal["ALTA", "MEDIA", "BAIXA"] = Field(
        default="MEDIA",
        description="Nível de confiabilidade das informações encontradas com base na clareza dos dados públicos"
    )
    fontes_consultadas: List[str] = Field(default_factory=list, description="URLs de referência ou portais públicos utilizados")


class CompanyEnrichmentRequest(BaseModel):
    """Requisição de enriquecimento de empresa."""
    company_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Nome da empresa a ser enriquecida",
        examples=["Matera", "Kavak", "Totvs", "Padaria Real Sorocaba"],
    )
    location_hint: Optional[str] = Field(
        default=None,
        description="Dica de localização (cidade ou estado) para desambiguação",
        examples=["Campinas SP", "São Paulo", "Belo Horizonte"],
    )
    segment_hint: Optional[str] = Field(
        default=None,
        description="Dica de segmento de mercado para afunilar empresas homônimas",
        examples=["Fintech", "Software", "Alimentos", "Logística"],
    )
    deep_scrape_website: bool = Field(
        default=True,
        description="Se true, faz o download do conteúdo da página oficial identificada para extração mais profunda",
    )
    people: List[str] = Field(
        default_factory=list,
        description="Lista de pessoas/executivos da empresa para busca direcionada no LinkedIn e QSA",
    )
    emails: List[str] = Field(
        default_factory=list,
        description="Lista de e-mails para validação SMTP e detecção do padrão corporativo",
    )
    phones: List[str] = Field(
        default_factory=list,
        description="Lista de telefones para higienização e validação de WhatsApp",
    )
    contacts: List[ContactInput] = Field(
        default_factory=list,
        description="Lista estruturada de contatos (nome, email, telefone, cargo)",
    )

    @model_validator(mode="before")
    @classmethod
    def resolve_aliases(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "company_name" not in data:
                for alt in ["name", "company", "empresa", "nome"]:
                    if alt in data and data[alt]:
                        data["company_name"] = data[alt]
                        break
            if "location_hint" not in data:
                for alt in ["location", "cidade", "estado"]:
                    if alt in data and data[alt]:
                        data["location_hint"] = data[alt]
                        break

            # normalize people
            peop = _normalize_string_list(data.get("people"))
            for alt in ["person", "person_name", "pessoa", "nome_pessoa", "target_people"]:
                if alt in data and data[alt]:
                    peop.extend(_normalize_string_list(data[alt]))

            # normalize emails
            em_list = _normalize_string_list(data.get("emails"))
            for alt in ["email", "mail", "e-mail"]:
                if alt in data and data[alt]:
                    em_list.extend(_normalize_string_list(data[alt]))

            # normalize phones
            ph_list = _normalize_string_list(data.get("phones"))
            for alt in ["phone", "telefone", "celular", "whatsapp", "tel"]:
                if alt in data and data[alt]:
                    ph_list.extend(_normalize_string_list(data[alt]))

            # if contacts list passed, merge into lists
            contacts_raw = data.get("contacts") or []
            if isinstance(contacts_raw, list):
                for c in contacts_raw:
                    if isinstance(c, dict):
                        c_name = c.get("nome") or c.get("name") or c.get("pessoa")
                        c_mail = c.get("email") or c.get("mail")
                        c_ph = c.get("telefone") or c.get("phone") or c.get("whatsapp")
                        if c_name and c_name not in peop:
                            peop.append(c_name)
                        if c_mail and c_mail not in em_list:
                            em_list.append(c_mail)
                        if c_ph and c_ph not in ph_list:
                            ph_list.append(c_ph)

            data["people"] = list(dict.fromkeys(peop))
            data["emails"] = list(dict.fromkeys(em_list))
            data["phones"] = list(dict.fromkeys(ph_list))

        return data


# ==============================================================================
# 2. Schemas for LinkedIn Decision Makers Discovery Pipeline
# ==============================================================================
class DecisionMakerProfile(BaseModel):
    """Perfil profissional de tomador de decisão identificado."""
    nome: str = Field(description="Nome do executivo/gestor")
    cargo: str = Field(description="Cargo atual ou principal título profissional")
    nivel_hierarquico: Literal[
        "C-Level / Sócio-Fundador",
        "Diretoria",
        "Gerência / Head",
        "Coordenação / Especialista",
        "Outro",
    ] = Field(description="Nível hierárquico na organização")
    departamento: str = Field(description="Área/Departamento (ex: Tecnologia, Vendas, Operações, Financeiro, Diretoria Geral)")
    linkedin_url: Optional[str] = Field(default=None, description="URL direta do perfil pessoal no LinkedIn (se identificada)")
    email_provavel: Optional[str] = Field(default=None, description="E-mail corporativo provável baseado no padrão da empresa")
    padrao_email: Optional[str] = Field(default=None, description="Formato/padrão de e-mail corporativo identificado na organização")
    status_email: Optional[str] = Field(default=None, description="Status de validação SMTP (ex: VALIDADO_SMTP, CATCH_ALL, INVALIDO, NAO_VERIFICADO)")
    telefone_contato: Optional[str] = Field(default=None, description="Telefone institucional ou direto para contato")
    localizacao: Optional[str] = Field(default=None, description="Cidade ou região informada no perfil")
    vinculo_atual_confirmado: bool = Field(
        default=True,
        description="Se as evidências indicam que a pessoa atua atualmente na empresa (e não apenas experiência passada)",
    )
    resumo_experiencia: Optional[str] = Field(default=None, description="Resumo das atribuições ou histórico profissional citado no snippet")
    origem_dado: Optional[str] = Field(
        default="LINKEDIN_OSINT",
        description="Origem: ENVIADO_PELO_USUARIO, QSA_RECEITA_FEDERAL ou LINKEDIN_OSINT",
    )
    pertence_ao_qsa: bool = Field(
        default=False,
        description="Indica se a pessoa consta no Quadro de Sócios e Administradores (QSA) oficial",
    )
    cargo_qsa: Optional[str] = Field(
        default=None,
        description="Cargo formal registrado na Receita Federal (se for sócio)",
    )
    whatsapp_valido: Optional[bool] = Field(
        default=None,
        description="Indica se o telefone possui WhatsApp ativo confirmado via Evolution API",
    )
    emails_associados: List[str] = Field(
        default_factory=list,
        description="Lista de emails corporativos ou diretos associados ao decisor",
    )
    telefones_associados: List[str] = Field(
        default_factory=list,
        description="Lista de telefones ou WhatsApp associados ao decisor",
    )


class CompanyEnrichmentResponse(BaseModel):
    """Resposta estruturada de enriquecimento de empresa."""
    status: str = Field(default="SUCCESS")
    nome_pesquisado: str
    dados_cadastrais: CadastralData
    presenca_digital: DigitalPresence
    perfil_mercado: MarketProfile
    inteligencia_comercial: CommercialIntelligence
    contatos_auditados: List[DecisionMakerProfile] = Field(
        default_factory=list,
        description="Dossiê das pessoas informadas pelo usuário ou decisores auditados",
    )
    auditoria_contatos: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Resumo técnico da auditoria de e-mails e telefones",
    )
    execution_time_seconds: Optional[float] = None


class DecisionMakersQueryPlan(BaseModel):
    """Consultas geradas pelo Gemini para encontrar decisores no LinkedIn via Google Search."""
    query_c_level: str = Field(description="Busca voltada a C-Level, Sócios, Founders e VPs")
    query_directors_heads: str = Field(description="Busca voltada a Diretores, Heads e Gerentes de áreas-chave")


class DecisionMakersRequest(BaseModel):
    """Requisição para busca de tomadores de decisão de uma empresa no LinkedIn."""
    company_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Nome da empresa para busca de decisores",
        examples=["Matera", "Kavak", "Totvs"],
    )
    website_or_domain: Optional[str] = Field(
        default=None,
        description="Domínio oficial da empresa (ex: matera.com) para auxiliar na precisão da busca",
    )
    target_departments: Optional[List[str]] = Field(
        default_factory=lambda: ["Diretoria", "Tecnologia", "Vendas", "Operações", "Financeiro"],
        description="Departamentos de interesse prioritário",
    )
    target_seniorities: Optional[List[str]] = Field(
        default_factory=lambda: ["C-Level", "Diretor", "VP", "Head", "Gerente", "Founder"],
        description="Níveis de senioridade buscados",
    )
    target_people: List[str] = Field(
        default_factory=list,
        description="Nomes específicos de pessoas a pesquisar prioritariamente",
    )
    people: List[str] = Field(
        default_factory=list,
        description="Alias para target_people",
    )
    provided_emails: List[str] = Field(
        default_factory=list,
        description="E-mails conhecidos para auxílio no mapeamento de decisores",
    )
    emails: List[str] = Field(
        default_factory=list,
        description="Alias para provided_emails",
    )
    provided_phones: List[str] = Field(
        default_factory=list,
        description="Telefones conhecidos para validação e associação",
    )
    phones: List[str] = Field(
        default_factory=list,
        description="Alias para provided_phones",
    )
    contacts: List[ContactInput] = Field(
        default_factory=list,
        description="Lista de contatos estruturados",
    )
    max_results: int = Field(default=10, ge=1, le=25, description="Quantidade máxima de perfis a retornar")

    @model_validator(mode="before")
    @classmethod
    def resolve_aliases(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "company_name" not in data:
                for alt in ["name", "company", "empresa", "nome"]:
                    if alt in data and data[alt]:
                        data["company_name"] = data[alt]
                        break

            # normalize people
            peop = _normalize_string_list(data.get("target_people") or data.get("people"))
            for alt in ["person", "person_name", "pessoa", "nome_pessoa"]:
                if alt in data and data[alt]:
                    peop.extend(_normalize_string_list(data[alt]))

            # normalize emails
            em_list = _normalize_string_list(data.get("provided_emails") or data.get("emails"))
            for alt in ["email", "mail", "e-mail"]:
                if alt in data and data[alt]:
                    em_list.extend(_normalize_string_list(data[alt]))

            # normalize phones
            ph_list = _normalize_string_list(data.get("provided_phones") or data.get("phones"))
            for alt in ["phone", "telefone", "celular", "whatsapp", "tel"]:
                if alt in data and data[alt]:
                    ph_list.extend(_normalize_string_list(data[alt]))

            contacts_raw = data.get("contacts") or []
            if isinstance(contacts_raw, list):
                for c in contacts_raw:
                    if isinstance(c, dict):
                        c_name = c.get("nome") or c.get("name")
                        c_email = c.get("email") or c.get("mail")
                        c_ph = c.get("telefone") or c.get("phone")
                        if c_name and c_name not in peop:
                            peop.append(c_name)
                        if c_email and c_email not in em_list:
                            em_list.append(c_email)
                        if c_ph and c_ph not in ph_list:
                            ph_list.append(c_ph)

            clean_people = list(dict.fromkeys(peop))
            clean_emails = list(dict.fromkeys(em_list))
            clean_phones = list(dict.fromkeys(ph_list))

            data["target_people"] = clean_people
            data["people"] = clean_people
            data["provided_emails"] = clean_emails
            data["emails"] = clean_emails
            data["provided_phones"] = clean_phones
            data["phones"] = clean_phones

        return data


class DecisionMakersResponse(BaseModel):
    """Resposta com lista estruturada de tomadores de decisão e estratégia de abordagem."""
    status: str = Field(default="SUCCESS")
    company_name: str
    total_encontrados: int
    decisores: List[DecisionMakerProfile] = Field(default_factory=list)
    analise_estrategica_contato: str = Field(
        description="Recomendação da IA de qual cargo/perfil deve ser abordado primeiro e por qual motivo estratégico"
    )
    execution_time_seconds: Optional[float] = None


class FullCompanyEnrichmentResponse(BaseModel):
    """Enriquecimento 360° unificado: dados da empresa + tomadores de decisão."""
    status: str = Field(default="SUCCESS")
    empresa: CompanyEnrichmentResponse
    decisores: DecisionMakersResponse
    execution_time_seconds: Optional[float] = None


# ==============================================================================
# 3. Schemas for Single-Call Unified Enrichment (Google + LinkedIn)
# ==============================================================================
class QuickEnrichRequest(BaseModel):
    """Requisição simplificada para enriquecimento completo (Google + LinkedIn + Contatos)."""
    name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Nome da empresa a enriquecer (ex: Matera, Nubank, Totvs)",
        examples=["Matera", "Nubank", "Kavak"],
    )
    location: Optional[str] = Field(
        default=None,
        description="Cidade ou Estado para auxiliar na desambiguação",
        examples=["Campinas SP", "São Paulo"],
    )
    deep_scrape: bool = Field(
        default=True,
        description="Se true, analisa o site oficial em profundidade",
    )
    people: List[str] = Field(
        default_factory=list,
        description="Lista de pessoas/executivos da empresa a pesquisar e qualificar",
    )
    emails: List[str] = Field(
        default_factory=list,
        description="Lista de e-mails para validação SMTP e detecção de padrão da empresa",
    )
    phones: List[str] = Field(
        default_factory=list,
        description="Lista de telefones para higienização e validação de WhatsApp",
    )
    contacts: List[ContactInput] = Field(
        default_factory=list,
        description="Lista estruturada de contatos (nome, email, telefone, cargo)",
    )

    @model_validator(mode="before")
    @classmethod
    def resolve_name_aliases(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "name" not in data:
                for alt in ["company_name", "company", "empresa", "nome"]:
                    if alt in data and data[alt]:
                        data["name"] = data[alt]
                        break
            if "location" not in data:
                for alt in ["location_hint", "cidade", "estado"]:
                    if alt in data and data[alt]:
                        data["location"] = data[alt]
                        break

            # normalize people
            peop = _normalize_string_list(data.get("people"))
            for alt in ["person", "person_name", "pessoa", "nome_pessoa", "target_people"]:
                if alt in data and data[alt]:
                    peop.extend(_normalize_string_list(data[alt]))

            # normalize emails
            em_list = _normalize_string_list(data.get("emails"))
            for alt in ["email", "mail", "e-mail"]:
                if alt in data and data[alt]:
                    em_list.extend(_normalize_string_list(data[alt]))

            # normalize phones
            ph_list = _normalize_string_list(data.get("phones"))
            for alt in ["phone", "telefone", "celular", "whatsapp", "tel"]:
                if alt in data and data[alt]:
                    ph_list.extend(_normalize_string_list(data[alt]))

            # if contacts list passed, merge into lists
            contacts_raw = data.get("contacts") or []
            if isinstance(contacts_raw, list):
                for c in contacts_raw:
                    if isinstance(c, dict):
                        c_name = c.get("nome") or c.get("name") or c.get("pessoa")
                        c_mail = c.get("email") or c.get("mail")
                        c_ph = c.get("telefone") or c.get("phone") or c.get("whatsapp")
                        if c_name and c_name not in peop:
                            peop.append(c_name)
                        if c_mail and c_mail not in em_list:
                            em_list.append(c_mail)
                        if c_ph and c_ph not in ph_list:
                            ph_list.append(c_ph)

            data["people"] = list(dict.fromkeys(peop))
            data["emails"] = list(dict.fromkeys(em_list))
            data["phones"] = list(dict.fromkeys(ph_list))

        return data


class GoogleEnrichmentData(BaseModel):
    """Dados cadastrais e operacionais extraídos via Google Search e site oficial."""
    razao_social: Optional[str] = None
    nome_fantasia: str
    cnpj: Optional[str] = None
    situacao_cadastral: Optional[str] = None
    sede: Optional[str] = None
    website_oficial: Optional[str] = None
    telefones: List[str] = Field(default_factory=list)
    emails: List[str] = Field(default_factory=list)
    setor: str
    nicho: Optional[str] = None
    porte_estimado: str
    o_que_faz: str
    produtos_servicos: List[str] = Field(default_factory=list)
    fontes_google: List[str] = Field(default_factory=list)


class LinkedInCompanyProfile(BaseModel):
    """Perfil institucional e corporativo da empresa no LinkedIn (Company Page)."""
    nome: Optional[str] = Field(None, description="Nome da empresa conforme exibido no LinkedIn")
    url: Optional[str] = Field(None, description="URL oficial da Company Page no LinkedIn")
    tagline: Optional[str] = Field(None, description="Slogan / Headline da empresa no LinkedIn")
    sobre: Optional[str] = Field(None, description="Descrição institucional (seção Sobre) no LinkedIn")
    setor: Optional[str] = Field(None, description="Setor / Indústria oficial segundo taxonomia do LinkedIn")
    faixa_funcionarios: Optional[str] = Field(None, description="Faixa de colaboradores cadastrada no LinkedIn (ex: 501-1.000 funcionários)")
    total_seguidores: Optional[str] = Field(None, description="Quantidade aproximada de seguidores no LinkedIn")
    sede: Optional[str] = Field(None, description="Localização da sede segundo o LinkedIn")
    ano_fundacao: Optional[str] = Field(None, description="Ano de fundação registrado no LinkedIn")
    tipo_empresa: Optional[str] = Field(None, description="Tipo de empresa (ex: Empresa privada, Sociedade Anônima)")
    especialidades: List[str] = Field(default_factory=list, description="Lista de especialidades cadastradas no perfil")
    vagas_url: Optional[str] = Field(None, description="URL da página de vagas no LinkedIn (/jobs)")


class LinkedInEnrichmentData(BaseModel):
    """Dados institucionais e decisores descobertos no LinkedIn."""
    company_url: Optional[str] = None
    empresa: Optional[LinkedInCompanyProfile] = None
    total_decisores_encontrados: int = 0
    decisores: List[DecisionMakerProfile] = Field(default_factory=list)


class CommercialStrategyData(BaseModel):
    """Inteligência comercial e gancho de abordagem."""
    dor_de_mercado_resolvida: Optional[str] = None
    sugestao_pitch_vendas: str
    melhor_ponto_de_contato: str
    nivel_confianca: str


class ContactAuditSummary(BaseModel):
    """Resumo consolidado da auditoria técnica dos contatos fornecidos pelo usuário."""
    total_emails_fornecidos: int = 0
    emails_validos: List[str] = Field(default_factory=list)
    padrao_corporativo_emails: Optional[str] = None
    emails_auditados: List[Dict[str, Any]] = Field(default_factory=list)
    total_telefones_fornecidos: int = 0
    telefones_com_whatsapp: List[str] = Field(default_factory=list)
    telefones_auditados: List[Dict[str, Any]] = Field(default_factory=list)


class UnifiedEnrichmentResponse(BaseModel):
    """Resposta consolidada de enriquecimento com Google e LinkedIn."""
    status: str = Field(default="SUCCESS")
    nome_pesquisado: str
    google: GoogleEnrichmentData
    linkedin: LinkedInEnrichmentData
    inteligencia_comercial: CommercialStrategyData
    contatos_enriquecidos_usuario: List[DecisionMakerProfile] = Field(
        default_factory=list,
        description="Dossiê detalhado das pessoas informadas pelo usuário na requisição com cargos e contatos auditados",
    )
    auditoria_contatos: Union[ContactAuditSummary, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Resumo da auditoria: e-mails testados por SMTP, padrão corporativo e status de WhatsApp",
    )
    execution_time_seconds: Optional[float] = None


# ==============================================================================
# 4. Schemas for Native SMTP Email Deliverability Verification
# ==============================================================================
class EmailVerifyRequest(BaseModel):
    """Requisição de verificação ativa de e-mail por handshake SMTP (zero-bounce)."""
    email: str = Field(..., description="Endereço de e-mail corporativo a ser testado", examples=["alessio.mainardi@zucchetti.com"])


class EmailVerifyResponse(BaseModel):
    """Resposta da verificação ativa de e-mail por SMTP."""
    email: str
    status: str = Field(description="VALIDADO_SMTP, CATCH_ALL, INVALIDO, SEM_MX, SINTAXE_INVALIDA ou ERRO_CONEXAO")
    valido: Optional[bool] = Field(default=None, description="True se a entrega for confirmada ou provável; False se rejeitado; None se inconclusivo")
    mx_host: Optional[str] = Field(default=None, description="Servidor de correio (MX) consultado")
    smtp_code: Optional[int] = Field(default=None, description="Código de resposta SMTP (ex: 250, 550)")
    is_catch_all: bool = Field(default=False, description="Indica se o domínio aceita qualquer endereço arbitrário")
    detalhe: str = Field(description="Explicação técnica do resultado")
    execution_time_seconds: Optional[float] = None

