"""
Pydantic Schemas for Google Search Scraping API.
"""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class GoogleSearchResultItem(BaseModel):
    position: int = Field(..., description="Ranking position in organic search results (1 to 10+)")
    title: str = Field(..., description="Title of the search result")
    url: str = Field(..., description="True destination URL")
    display_url: str = Field(default="", description="Visible breadcrumb or domain")
    snippet: str = Field(default="", description="Snippet / Meta description summary")
    date: Optional[str] = Field(default=None, description="Publication or update date if present")
    sitelinks: List[Dict[str, str]] = Field(default_factory=list, description="Sub-links found under this result")


class GoogleSearchRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Search term or query to execute on Google",
        examples=["inteligencia artificial para empresas", "melhores frameworks python 2026"],
    )
    num_results: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Target number of organic results (default: 10)",
    )
    lang: str = Field(
        default="pt-BR",
        description="Language code for Google Search (hl parameter, e.g. pt-BR, en-US)",
    )
    country: str = Field(
        default="br",
        description="Country code for Google Search (gl parameter, e.g. br, us)",
    )
    format: Literal["json", "markdown"] = Field(
        default="json",
        description="Response format: structured JSON or clean Markdown optimized for LLM prompting",
    )
    capture_screenshot: bool = Field(
        default=False,
        description="Capture full-page screenshot of the Google Search page for auditing/debugging",
    )


class GoogleSearchResponse(BaseModel):
    query: str
    total_results: int
    organic_results: List[GoogleSearchResultItem]
    people_also_ask: List[str] = Field(
        default_factory=list,
        description="People Also Ask (Perguntas Frequentes / Relacionadas)",
    )
    related_searches: List[str] = Field(
        default_factory=list,
        description="Related searches suggested by Google at the bottom of the page",
    )
    ai_overview: Optional[str] = Field(
        default=None,
        description="AI Overview or knowledge panel answer if generated by Google",
    )
    screenshot_path: Optional[str] = Field(
        default=None,
        description="Server path to the captured screenshot if enabled",
    )
